import curses

DEFAULT_BACKGROUND_COLOR = curses.COLOR_BLACK
TYPO_FLASH_COLOR = curses.COLOR_RED
OUR_BULLETS_COLOR = curses.COLOR_CYAN
ENEMY_BULLETS_COLOR = curses.COLOR_BLUE

NUMBER_OF_BATTLE_ROWS = 30
NUMBER_OF_BATTLE_COLUMNS = 100

DISPLAY_WIDTH = 120
DISPLAY_HEIGHT = 50
ACTION_PADDING_TOP = 10
ACTION_PADDING_BOTTOM = 10
MAX_STRING_LEN = 20
dictionary = {
        0 : 'candy',
        }
