import curses

DEFAULT_BACKGROUND_COLOR = curses.COLOR_BLACK
TYPO_FLASH_COLOR = curses.COLOR_RED
OUR_BULLETS_COLOR = curses.COLOR_CYAN
ENEMY_BULLETS_COLOR = curses.COLOR_BLUE

DISPLAY_WIDTH = 120
DISPLAY_HEIGHT = 40
